### ISSUE TITLE
Problem with file name auto fix

### ISSUE THREAD

**Issue by vuongxuongminh** [kenjis/codeigniter3-filename-checker#1]
In [Check L29](https://github.com/kenjis/codeigniter3-filename-checker/blob/master/controllers/Check.php#L29) default value of `$fix` is `no` and isn't identical when validate at [Check L112](https://github.com/kenjis/codeigniter3-filename-checker/blob/master/controllers/Check.php#L112) and filename always auto fix.

**Comment by kenjis** [comment]
https://github.com/kenjis/codeigniter3-filename-checker/blob/master/controllers/Check.php#L112 is `$this->fix`, not `$fix`.
